version: "3"

services:
  server:
    container_name: gocd-server
    image: gocd/gocd-server:v18.12.0
    restart: always
    expose:
      - 8153
      - 8154
    volumes:
      - ./godata:/godata
      - ./.ssh:/home/go/.ssh
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - VIRTUAL_PORT=8153
    networks:
      - frontend
      - backend
  agent:
    container_name: gocd-agent
    image: gocd/gocd-agent-alpine-3.8:v18.12.0
    restart: always
    volumes:
      - ./godata:/godata
      - ./.ssh:/home/go/.ssh
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - GO_SERVER_URL=https://server:8154/go
      - AGENT_AUTO_REGISTER_KEY=${AGENT_AUTO_REGISTER_KEY}
    networks:
      - backend
    depends_on:
      - server

networks:
  frontend:
    external:
      name: nginx-proxy
  backend:
