version: "3"

services:
  server:
    container_name: gocd-server
    image: gocd/gocd-server:v18.12.0
    restart: always
    expose:
      - 8153
      - 8154
    volumes:
      - ./godata:/godata:delegated
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - VIRTUAL_PORT=8153
      - LETSENCRYPT_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    networks:
      - frontend
      - backend
  agent:
    container_name: gocd-agent
    image: ran91/gocd-agent
    restart: always
    volumes:
      - ./godata:/godata:delegated
      - ./.ssh:/home/go/.ssh:delegated
      - ${PROJECTS_DIR}:${PROJECTS_DIR}:delegated
      - /var/run/docker.sock:/var/run/docker.sock:delegated
    environment:
      - GO_SERVER_URL=https://server:8154/go
      - AGENT_AUTO_REGISTER_KEY=${AGENT_AUTO_REGISTER_KEY}
    networks:
      - backend
    depends_on:
      - server

networks:
  frontend:
    external:
      name: nginx-proxy
  backend:
