version: "3"

services:
  server:
    container_name: ${COMPOSE_PROJECT_NAME}-server
    image: gocd/gocd-server:v18.12.0
    restart: always
    expose:
      - 8153
      - 8154
    volumes:
      - ./data:/godata
      - ~/.ssh:/home/go/.ssh
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST},www.${VIRTUAL_HOST}
      - VIRTUAL_PORT=8153
      - LETSENCRYPT_HOST=${VIRTUAL_HOST},www.${VIRTUAL_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    networks:
      - frontend
      - backend
  agent:
    container_name: ${COMPOSE_PROJECT_NAME}-agent
    image: ran91/gocd-agent
    restart: always
    volumes:
      - ./data:/godata
      - ~/.ssh:/home/go/.ssh
      - ${PROJECTS_DIR}:${PROJECTS_DIR}
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - GO_SERVER_URL=https://server:8154/go
      - AGENT_AUTO_REGISTER_KEY=${AGENT_AUTO_REGISTER_KEY}
      - AGENT_AUTO_REGISTER_HOSTNAME=${AGENT_AUTO_REGISTER_HOSTNAME}
    networks:
      - backend
    depends_on:
      - server

networks:
  frontend:
    external:
      name: nginx-proxy
  backend:
